show tables
CREATE OR REPLACE WAREHOUSE lab_wh_WWH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

  CREATE OR REPLACE DATABASE retail_db_WWH;
CREATE OR REPLACE SCHEMA retail_db_WWH.raw;
CREATE OR REPLACE SCHEMA retail_db_WWH.analytics;
 
USE WAREHOUSE lab_wh_WWH;
USE DATABASE retail_db_WWH;
USE SCHEMA retail_db_WWH.raw;

SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER LIMIT 10;

